spring.application.name=AirBnb

# Connection URL format -> jdbc:postgresql://<host>:<port>/<database_name>
spring.datasource.url=jdbc:postgresql://localhost:5432/AirBnb
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Credentials
spring.datasource.username=ram
spring.datasource.password=
